### ISSUE TITLE
How to install this ok Kodi?

### ISSUE THREAD

**Issue by stefs22** [b-jesch/plugin.video.ipcams#12]
Can someone explain me how to install this?

**Comment by b-jesch** [comment]
Download and install Kodinerds Repo (https://repo.kodinerds.net Red Button) and choose from Addons - Install from Repository - Kodinerds Addon Repo - Video Addons Surveillance Cameras.

Or download direct from Kodinerds Repo and install from Zip (type in search field: surv)

**Comment by stefs22** [comment]
Thank you, i am not sure what to type on camera location?
I want 3 cameras to show.
Can i set this to open all 3 cam on once?

**Comment by b-jesch** [comment]
Type what you want, e.g. "Backdoor Camera View".

> Can i set this to open all 3 cam on once?

No.

**Comment by stefs22** [comment]
than you, it works good, but i looking for something to show all 3 cams.

**Comment by b-jesch** [comment]
Since Kodi doesn't support PIP feature (Picture in Picture) it isn't possible to show 3 streams at same time.

**Comment by stefs22** [comment]
tnx
