### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by graysky2** [b-jesch/plugin.video.ipcams#6]
I saw you pushed some commits to the matrix branch but there is not an entry in the official repos.  Is the code good enough as-is for Matrix?  Do you plan on supporting Nexus?  Thanks.

**Comment by b-jesch** [comment]
This plugin is commited to the Kodinerds Repo: https://repo.kodinerds.net
I don't push commits to the official Kodi Repo. Nexus support will come when Nexus comes ;)

**Comment by graysky2** [comment]
OK, thanks.  Too bad it cannot be included in the official kodi repo.  Any reason why?

**Comment by b-jesch** [comment]
Personal reasons.
