### ISSUE TITLE
Ubuntu upgrade killed functionality

### ISSUE THREAD

**Issue by assignonward** [b-jesch/plugin.video.ipcams#7]
I just upgraded my Ubuntu from 18.04.6 to 20.04.3 and I believe it upgraded Kodi as part of the process.  The only plugin I have installed is the Surveillance Monitor v0.0.3. It still remembers all my cameras and their address strings, but when I click on them in the plugin window, nothing happens.

Kodi reports it is from Debian 18.6 Compiled 2020-04-03.

My cameras still stream to VNC, but your Kodi plugin is a much nicer way to access them.  Do you have any ideas how I might get it working again?

**Comment by b-jesch** [comment]
The Kodi team itself recommends not to install Kodi from the Ubuntu sources, but from the Kodi PPAs. There's no support for foreign sources like Debian:

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

So the best way is uninstall Kodi and reinstall it from kodi-team.ppa. At the same time you get the latest version (Kodi 19.3 Matrix).

If you don't want to upgrade this way please provide a debug log of Kodi with the addon running and performig some actions on this addon.

Regards
